server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_app
    username: postgres
    password: 654321
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Propiedades personalizadas para JWT
jwt:
  secret: f83YgV2zP0pR4Ks9LcQwN3aT7uXxB6Md
  expiration: 86400000

# Logging (opcional, Ãºtil para debug)
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#blockchain:
 # node-url: http://127.0.0.1:8545
  #private-key: ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
#contract:
 # address: "0x5FbDB2315678afecb367f032d93F642f64180aa3"*/
#blockchain:
#  rpc-url: http://localhost:8545
 #contract-address: "0x05EfdBd486b0e0b3A2Cdf0F73d0719e08b5DDbAC"
